// ~~ Generated by projen. To modify, edit .projenrc.js and run "pnpm exec projen".

import { defineProject } from 'vitest/config'

export default defineProject({
	test: {
		name: 'projen.component.postcss',
		include: ['test/**/*.spec.ts'],
	},
})
