// ~~ Generated by projen. To modify, edit .projenrc.js and run "pnpm exec projen".

import { defineBuildConfig } from 'unbuild'
import { compositePreset } from './src'

export default defineBuildConfig({
	name: 'utils.unbuild-composite-preset',
	declaration: true,
	clean: true,
	entries: ['./src/index'],
	sourcemap: true,
	rollup: {
		emitCJS: true,
		cjsBridge: true,
		esbuild: {
			treeShaking: true,
			sourcemap: true,
		},
	},
	preset: compositePreset(),
})
