// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { defineBuildConfig, type BuildConfig } from 'unbuild'

const config: BuildConfig = {
	name: '@arroyodev-llc/projen.component.typescript-source-file',
	declaration: true,
}
export default defineBuildConfig(config)
