// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".

import { defineConfig } from 'vitest/config'

export default defineConfig({
	test: {
		name: 'components',
		include: ['test/**/*.spec.ts'],
		pool: 'threads',
		projects: [
			'./packages/utils/fs/vitest.config.ts',
			'./packages/utils/ts-ast/vitest.config.ts',
			'./packages/utils/projen/vitest.config.ts',
			'./packages/utils/projen-builder/vitest.config.ts',
			'./packages/utils/firebase/vitest.config.ts',
			'./packages/construct/awscdk/github-pipeline/vitest.config.ts',
			'./packages/projen/component/vite/vitest.config.ts',
			'./packages/projen/component/dir-env/vitest.config.ts',
			'./packages/projen/component/tailwind/vitest.config.ts',
			'./packages/projen/component/postcss/vitest.config.ts',
			'./packages/projen/component/awscdk-ts-esm-lambda/vitest.config.ts',
			'./packages/vue/ui/text/vitest.config.ts',
			'./packages/vue/ui/button/vitest.config.ts',
		],
	},
})
