// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".

import { defineConfig } from 'vitest/config'

export default defineConfig({
	test: {
		name: 'components',
		include: ['test/**/*.spec.ts'],
		threads: true,
	},
})
