// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
	name: 'projen.component.tailwind',
	declaration: true,
	clean: true,
	entries: ['./src/index'],
	sourcemap: true,
	rollup: {
		emitCJS: true,
		cjsBridge: true,
		esbuild: {
			treeShaking: true,
			sourcemap: true,
		},
	},
})
