// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

declare module '*.vue' {
	import { type DefineComponent } from 'vue'
	// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/ban-types
	const component: DefineComponent<{}, {}, any>
	export default component
}
