// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import VueMacros from 'unplugin-vue-macros/vite'
import { defineConfig } from 'vite'

export default defineConfig({
	build: {
		emptyOutDir: true,
		sourcemap: 'inline',
		lib: { entry: 'src/index.ts', formats: ['es', 'cjs'] },
	},
	resolve: { dedupe: ['vue'] },
	plugins: [
		VueMacros({
			plugins: {
				vue: vue(),
			},
		}),
		vueJsx(),
	],
})
