import os from 'node:os'
import path from 'node:path'
import { awscdk, DependencyType, Testing, typescript } from 'projen'
import { beforeEach, describe, expect, test } from 'vitest'
import { AwsCdkTsEsmLambda } from '../src'

interface TestContext {
	outdir: string
	project: typescript.TypeScriptProject
	lambdaFunction: awscdk.LambdaFunction
}

describe('AwsCdkTsEsmLambda', () => {
	beforeEach<TestContext>(async (ctx) => {
		const outdir = path.join(os.tmpdir(), ctx.task.id)
		ctx.outdir = outdir
		ctx.project = new typescript.TypeScriptProject({
			name: ctx.task.id,
			outdir,
			defaultReleaseBranch: 'main',
		})
		ctx.lambdaFunction = new awscdk.LambdaFunction(ctx.project, {
			entrypoint: path.join('src', 'test.lambda.ts'),
			cdkDeps: new awscdk.AwsCdkDepsJs(ctx.project, {
				cdkVersion: '2.162.1',
				dependencyType: DependencyType.RUNTIME,
			}),
		})
	})

	test<TestContext>('renders as expected', (ctx) => {
		const file = ctx.project.tryFindFile('src/test-function.ts')
		new AwsCdkTsEsmLambda(ctx.project, {
			filePath: file.path,
		})
		const synth = Testing.synth(ctx.project)
		expect(synth['src/test-function.ts']).toBeDefined()
		expect(synth['src/test-function.ts']).toMatchInlineSnapshot(`
			"// ~~ Generated by projen. To modify, edit .projenrc.js and run \\"npx projen\\".

			// ~~ Generated by projen. To modify, edit .projenrc.js and run \\"npx projen\\".
			import * as lambda from 'aws-cdk-lib/aws-lambda';
			import { Construct } from 'constructs';
			import { fileURLToPath } from \\"node:url\\";
			import * as path from 'path';

			/**
			 * Props for TestFunction
			 */
			export interface TestFunctionProps extends lambda.FunctionOptions {
			}

			/**
			 * An AWS Lambda function which executes src/test.
			 */
			export class TestFunction extends lambda.Function {
			  constructor(scope: Construct, id: string, props?: TestFunctionProps) {
			      const __filename = fileURLToPath(import.meta.url);
			      const __dirname = dirname(__filename);
			    super(scope, id, {
			      description: 'src/test.lambda.ts',
			      ...props,
			      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
			      handler: 'index.handler',
			      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/test.lambda')),
			    });
			    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
			  }
			}"
		`)
	})
})
