// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import type { RollupOptions } from 'rollup'
import vue from 'rollup-plugin-vue'
import { defineBuildConfig, type BuildConfig, type BuildContext } from 'unbuild'

const config: BuildConfig = {
	name: '@arroyodev-llc/vue.ui.text',
	declaration: true,
	clean: true,
	entries: ['./src/index'],
	rollup: { emitCJS: true },
	hooks: {
		'rollup:options'(_: BuildContext, options: RollupOptions) {
			// @ts-expect-error ignore rollup options.
			options.plugins.push(vue())
		},
	},
}
export default defineBuildConfig(config)
