// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { type RollupOptions } from 'rollup';
import vue from 'rollup-plugin-vue';
import { defineBuildConfig, type BuildConfig, type BuildContext } from 'unbuild';

const config: BuildConfig = {
  name: '@arroyodev-llc/components.vue.ui.text',
  declaration: true,
  hooks: {
    'rollup:options': (ctx: BuildContext, options: RollupOptions) => {
            							// @ts-expect-error ignore rollup.
            							options.plugins.push(vue());
            						},
  },
};
export default defineBuildConfig(config);