// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import VueMacros from 'unplugin-vue-macros/vite'
import { defineConfig } from 'vite'
import dts from 'vite-plugin-dts'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({
	plugins: [
		tsconfigPaths(),
		dts({ entryRoot: 'src' }),
		VueMacros({
			plugins: {
				vue: vue(),
			},
		}),
		vueJsx(),
	],
	build: {
		lib: {
			entry: 'src/index.ts',
			fileName: 'index',
			name: '@arroyodev-llc/vue.ui.text',
			formats: ['es', 'cjs'],
		},
		rollupOptions: {
			external: ['vue', '@vue/runtime-dom'],
		},
	},
	resolve: {
		dedupe: ['vue'],
	},
})
