// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import vue from "@vitejs/plugin-vue";
import vueJsx from "@vitejs/plugin-vue-jsx";
import VueMacros from "unplugin-vue-macros/vite";
import { defineConfig } from "vite";

export default defineConfig({
	build: {
		outDir: "./dist",
		lib: { entry: "./src/index", name: "vue.ui.text" },
		// emptyOutDir: true,
		// sourcemap: 'inline',
		// lib: { entry: 'src/index.ts', formats: ['es', 'cjs'] },
	},
	resolve: { dedupe: ["vue"] },
	optimizeDeps: {
		include: ["vue"],
	},
	plugins: [
		VueMacros({
			plugins: {
				vue: vue(),
				vueJsx: vueJsx(),
			},
		}),
	],
});
