// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".
import type { javascript } from 'projen';
import type { TypeScriptCompilerOptions } from './';

/**
 * TypeScriptConfigOptions
 */
export interface TypeScriptConfigOptions {
  /**
   * Specifies a list of glob patterns that match TypeScript files to be included in compilation.
   * @default - all .ts files recursively
   * @stability experimental
   */
  readonly include?: Array<string>;
  /**
   * @default "tsconfig.json"
   * @stability experimental
   */
  readonly fileName?: string;
  /**
   * Base `tsconfig.json` configuration(s) to inherit from.
   * @stability experimental
   * @remarks Must provide either `extends` or `compilerOptions` (or both).
   */
  readonly extends?: javascript.TypescriptConfigExtends;
  /**
   * Filters results from the "include" option.
   * @default - node_modules is excluded by default
   * @stability experimental
   */
  readonly exclude?: Array<string>;
  /**
   * Compiler options to use.
   * @stability experimental
   * @remarks Must provide either `extends` or `compilerOptions` (or both).
   */
  readonly compilerOptions?: TypeScriptCompilerOptions;
}
