// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { defineProject } from 'vitest/config'

export default defineProject({
	test: { name: 'utils.projen', include: ['test/**/*.spec.ts'] },
})
