// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { defineBuildConfig, type BuildConfig } from 'unbuild'

const config: BuildConfig = {}
export default defineBuildConfig(config)
